### ISSUE TITLE
include tags and other metadata

### ISSUE THREAD

**Issue by arcturus140** [dpjayasekara/boostnote-github-sync#20]
Did you consider synchronizing all metadata from boostnote notes and snippets with markdown files? Metadata could be added to [YAML front matter](https://yaml.org/spec/1.2/spec.html#id2760395).

This section is invisible for most markdown renderer. Also works with BN. An example could look like:

```
---
createdAt: "2018-09-25T09:05:00.937Z"
updatedAt: "2019-05-23T14:05:01.657Z"
type: "MARKDOWN_NOTE"
folder: "2826e081a3ec6d795f77"
filename: blabla.cson""
title: "some title"
tags: "a, b, c"
---
```

Though it is being displayed on github and bitbucket (others untested). Maybe a comment section could be used, instead:

```
<!--
createdAt: "2018-09-25T09:05:00.937Z"
updatedAt: "2019-05-23T14:05:01.657Z"
type: "MARKDOWN_NOTE"
folder: "2826e081a3ec6d795f77"
filename: blabla.cson""
title: "some title"
tags: "a, b, c"
-->
```

**Comment by deepal** [comment]
@arcturus140 Thanks for the contribution. I plan to support this by allowing syncing raw notes in `.cson` format to GitHub. This not only allows preserving metadata but also allows bi-directional syncing with GitHub (with the current implementation, it is only possible to sync to GitHub only, not the other way around). Please follow up with the issue #5 .

**Comment by arcturus140** [comment]
yes, I meant this as an alternative to #5, but storing raw notes preserves the metadata as well.
